#!/usr/bin/env python3
"""Build the per-family rule ledger from each skill's evidence document.

usage: build-ledger.py <family> > evidence/<family>/rules.md

One row per rule in the family, with the status the evidence document gives it.
The source of truth is a `## Ledger` table inside `evidence/<family>/skills/<skill>.md`,
so a rule's status lives next to the reasoning for it rather than in a second place
that drifts.

A rule present in the skill but absent from the ledger is an error: every rule a
project installs has to carry a status, including `unmeasured`.
"""
import re, sys, pathlib

STATUSES = {'measured', 'satisfied-unaided', 'not-landing', 'not-tempted', 'retired', 'null'}

family = sys.argv[1] if len(sys.argv) > 1 else 'android'
skills_dir = pathlib.Path('skills') / family
ev_dir = pathlib.Path('evidence') / family / 'skills'

rows, errors = [], []

for f in sorted(skills_dir.glob('*/SKILL.md')):
    skill = f.parent.name
    body = f.read_text().split('---', 2)[2]
    fm = f.read_text().split('---', 2)[1]
    live = re.findall(r'^- \*\*([A-Z0-9]+-\d+)\*\*', body, re.M)
    ret = re.search(r'^retired:\s*\[(.*?)\]', fm, re.M | re.S)
    retired = [x.strip() for x in ret.group(1).split(',') if x.strip()] if ret else []

    ev = ev_dir / f'{skill}.md'
    if not ev.exists():
        errors.append(f'{family}/{skill}: no evidence document at {ev}')
        continue

    seen = {}
    block = re.search(r'^## Ledger\s*\n(.*?)(?=\n## |\Z)', ev.read_text(), re.S | re.M)
    if block:
        for line in block.group(1).split('\n'):
            m = re.match(r'\s*\|\s*`?([A-Z0-9]+-\d+)`?\s*\|\s*(\S+)\s*\|\s*(.*?)\s*\|', line)
            if m:
                rid, status, note = m.group(1), m.group(2).strip('`'), m.group(3)
                if status not in STATUSES:
                    errors.append(f'{family}/{skill} {rid}: unknown status `{status}`')
                seen[rid] = (status, note)

    for rid in live:
        if rid not in seen:
            errors.append(f'{family}/{skill} {rid}: in the skill but not in the ledger')
        else:
            rows.append((skill, rid, *seen[rid]))
    for rid in retired:
        if rid in seen:
            rows.append((skill, rid, *seen[rid]))

if errors:
    for e in errors:
        print(f'ERROR  {e}', file=sys.stderr)
    sys.exit(1)

counts = {}
for _, _, status, _ in rows:
    counts[status] = counts.get(status, 0) + 1

print(f'# Rule ledger: `{family}`\n')
print('Every rule in the family, and what is known about it. Statuses are defined in')
print('[spec/ADMISSION.md](../../spec/ADMISSION.md).\n')
print('| status | count |')
print('|---|---|')
for s in ('measured', 'satisfied-unaided', 'not-landing', 'not-tempted', 'retired', 'null'):
    if s in counts:
        print(f'| `{s}` | {counts[s]} |')
print(f'\n**Generated by `scripts/build-ledger.py {family}`. Do not edit.**\n')
print('| skill | rule | status | evidence |')
print('|---|---|---|---|')
for skill, rid, status, note in rows:
    print(f'| `{family}/{skill}` | `{rid}` | `{status}` | {note} |')
